### ISSUE TITLE
What is wrong with me

### ISSUE THREAD

**Issue by ghost** [JLWalsh/Nest-ProviderBuilders#1]
I have an issue with myself. I starred this without me knowing what is going on! I don't know what this project does. Can someone help me resolve this issue as it is fatal and must be fixed...

**Comment by JLWalsh** [comment]
Hahaha, so this is a simple tool to setup [NestJS providers](https://docs.nestjs.com/providers). Basically, providers allow you to setup instances, so that they may be injected using `@Inject`. It's an awesome feature, but I found that the way of setting up the providers was a bit clunky, so I took inspiration from how other injection frameworks allow you to declare providers, and I made this little library!

Hope this cleared some things! :)

**Comment by ghost** [comment]
Ok. I think the issue is solved and progress can continue.
